# fly.toml app configuration file generated for zordle on 2025-01-28T23:45:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zordle'
primary_region = 'hkg'

[build]
  dockerfile = "Dockerfile"   # Explicitly tell Fly.io to use your Dockerfile

[http_service]
  internal_port = 80          # Matches the port exposed by Nginx
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
