# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter

name: Lint Code Base

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Disabled linting checks because annoying

      # - name: Lint Code Base
      #   uses: github/super-linter@v4
      #   env:
      #     VALIDATE_ALL_CODEBASE: false # false: Lint only the changed files, not the entire codebase.
      #     DEFAULT_BRANCH: "master"
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     JAVASCRIPT_ES_CONFIG: . # Ensure the Github action workflow uses my eslint.config.js